### ISSUE TITLE
D compiler needed for building

### ISSUE THREAD

**Issue by epsilon-0** [myfreeweb/numbernine#1]
I am trying to install the DE and am currently running in to the following error
```
meson.build:1:0: ERROR: Could not find any supported D compiler.
```

If you could tell what I need, that would be awesome!

I really want to give this a spin.

**Comment by valpackett** [comment]
wow, I didn't expect anyone trying this out right now, I rewrote the settings app in D like yesterday :) the whole thing is quite early and incomplete, so don't expect anything.

[LDC](https://github.com/ldc-developers/ldc) is the recommended D compiler, but DMD and GDC might work too of course.

You'll also need [GtkD](https://github.com/gtkd-developers/GtkD) installed (as a shared library)

**Comment by epsilon-0** [comment]
Dope af.
I'll add LDC to the needed dependencies on gentoo.

Unfortunately, this will result in needing an unofficial repository for gentoo: https://github.com/gentoo/dlang

If there is anyway in which to make this as little dependencies as possible on unofficial repos, let me know.

**Comment by valpackett** [comment]
> the needed dependencies on gentoo

Please don't package numbernine yet! It is way too early for packaging.

**Comment by epsilon-0** [comment]
Haha, no worries, I am going to start the packaging process and then it can be updated whenever there are changes upstream (here)

**Comment by epsilon-0** [comment]
Though it looks like you are using FreeBSD which is also a pretty dope system!
